name: Deploy Portfolio from Subfolder

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Using latest checkout version
      
      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4  # Updated to v4
      
      # KEY STEP: Upload the specific subfolder
      - name: Upload Portfolio Site
        uses: actions/upload-pages-artifact@v4  # Updated to v4 (latest)
        with:
          path: "my-projects/dasdev-portfolio/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-upload
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4  # Updated to v4 (latest)
